learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path
from .views import (IndexView, TopicView, TopicDetailView,
                    TopicCreateView, EntryCreateView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('topics/', TopicView.as_view(), name='topics'),
    path('topics/<int:pk>', TopicDetailView.as_view(),
        name='topic_detail'),
    path('topics/new/', TopicCreateView.as_view(), name='new_tospic'),
    path('topics/<int:topic_pk>/entry/', EntryCreateView.as_view(), name='new_entry'),
]

learning_logs/models.py
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation about the model"""
        return self.text

    def get_absolute_url(self):
        return reverse('topics')


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return f"{self.text[:50]}..."

    def get_absolute_url(self):
        return reverse('topic_detail', args=[self.topic.pk])

learning_logs/views.py
from django.views.generic import (TemplateView, ListView,
                                  DetailView)
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404

from .models import Topic, Entry
from .form import EntryForm


class IndexView(TemplateView):
    template_name = 'index.html'


class TopicView(ListView):
    model = Topic
    template_name = 'topic.html'


class TopicDetailView(DetailView):
    model = Topic
    template_name = 'topic_detail.html'


class TopicCreateView(CreateView):
    model = Topic
    fields = ['text']
    template_name = 'topic_new.html'


class EntryCreateView(CreateView):
    form_class = EntryForm
    model = Entry
    template_name = 'entry_new.html'

    def dispatch(self, request, *args, **kwargs):
        self.topic = get_object_or_404(Topic,
                                       pk=kwargs['topic_pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.topic = self.topic
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Learnig Log</title>
  </head>
  <body>
    <p>
      <a href="{% url 'index' %}">Learning Log</a>
      <a href="{% url 'topics' %}">Topics</a>
    </p>
    {% block content %}
    {% endblock content %}
  </body>
</html>

templates/entry_new.html
{% extends 'base.html' %}

{% block content %}
<p>Add a new topic</p>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add Entry" />
</form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Learning Log helps you keep track of your learning,
for any topic you're learning about.</p>

{% endblock content %}

templates/topic.html
{% extends 'base.html' %}

{% block content %}

<p>Topics</p>

<ul>
  {% for topic in object_list %}
    <li> <a href="{% url 'topic_detail' topic.pk %}">{{ topic }}</a></li>
  {% empty %}
    <li>No topics have been added yet.</li>
  {% endfor %}
</ul>
<a href="{% url 'new_tospic' %}">Add a new topic</a>
{% endblock content %}

templates/topic_detail.html
{% extends 'base.html' %}

{% block content %}
<p>Topic: {{ topic }}</p>
<ul>
  {% for entry in topic.entry_set.all %}
    <li>
      <p>{{ entry.date_added }}</p>
      <p>{{ entry.text|linebreaks }}</p>
    </li>
  {% empty %}
    <li>There are no entries for this topic yet.</li>
  {% endfor %}
</ul>
<a href="{% url 'new_entry' topic.pk %}">Add Entry</a>

{% endblock content %}

templates/topic_new.html
{% extends 'base.html' %}

{% block content %}
<p>Add a new topic</p>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add topic" />
</form>
{% endblock content %}